CREATE TABLE import_batch (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    internal_hash   VARCHAR(64)  NOT NULL,
    settlement_hash VARCHAR(64)  NOT NULL,
    imported_at     TIMESTAMP    NOT NULL,
    internal_count  INT          NOT NULL,
    settlement_count INT         NOT NULL,
    quarantined_count INT        NOT NULL,
    CONSTRAINT uq_import_batch_hashes UNIQUE (internal_hash, settlement_hash)
);

CREATE TABLE internal_transaction (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id            BIGINT       NOT NULL REFERENCES import_batch (id),
    internal_txn_id     VARCHAR(64)  NOT NULL,
    merchant_id         VARCHAR(32)  NOT NULL,
    merchant_ref        VARCHAR(64)  NOT NULL,
    card_type           VARCHAR(16)  NOT NULL,
    card_last4          VARCHAR(8)   NOT NULL,
    gross_amount        DECIMAL(15, 2) NOT NULL,
    txn_type            VARCHAR(8)   NOT NULL,
    captured_at         TIMESTAMP    NOT NULL,
    expected_interchange DECIMAL(15, 2) NOT NULL,
    expected_processor  DECIMAL(15, 2) NOT NULL,
    expected_net        DECIMAL(15, 2) NOT NULL
);

CREATE INDEX idx_internal_txn_batch ON internal_transaction (batch_id);
CREATE INDEX idx_internal_txn_ref ON internal_transaction (merchant_ref);

CREATE TABLE settlement_record (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id         BIGINT       NOT NULL REFERENCES import_batch (id),
    network_ref      VARCHAR(64)  NOT NULL,
    merchant_ref     VARCHAR(64)  NOT NULL,
    merchant_id      VARCHAR(32)  NOT NULL,
    card_type        VARCHAR(16)  NOT NULL,
    card_last4       VARCHAR(8)   NOT NULL,
    settled_amount   DECIMAL(15, 2) NOT NULL,
    interchange_fee  DECIMAL(15, 2) NOT NULL,
    processor_fee    DECIMAL(15, 2) NOT NULL,
    settlement_date  DATE         NOT NULL
);

CREATE INDEX idx_settlement_batch ON settlement_record (batch_id);
CREATE INDEX idx_settlement_network ON settlement_record (network_ref);

CREATE TABLE quarantined_row (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id     BIGINT       NOT NULL REFERENCES import_batch (id),
    side         VARCHAR(16)  NOT NULL,
    line_number  INT          NOT NULL,
    source_id    VARCHAR(64),
    raw_payload  VARCHAR(4000) NOT NULL,
    reason       VARCHAR(32)  NOT NULL
);

CREATE INDEX idx_quarantine_batch ON quarantined_row (batch_id);

CREATE TABLE recon_run (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id    BIGINT        NOT NULL REFERENCES import_batch (id),
    run_at      TIMESTAMP     NOT NULL,
    tolerance   DECIMAL(10, 4) NOT NULL,
    window_min  INT           NOT NULL,
    window_max  INT           NOT NULL
);

CREATE INDEX idx_recon_run_batch ON recon_run (batch_id);

CREATE TABLE recon_outcome (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id                  BIGINT       NOT NULL REFERENCES recon_run (id),
    internal_transaction_id BIGINT       REFERENCES internal_transaction (id),
    outcome                 VARCHAR(32)  NOT NULL,
    detail                  VARCHAR(500),
    settlement_day_offset   INT
);

CREATE INDEX idx_recon_outcome_run ON recon_outcome (run_id);

CREATE TABLE recon_outcome_settlement (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    outcome_id     BIGINT NOT NULL REFERENCES recon_outcome (id),
    settlement_id  BIGINT NOT NULL REFERENCES settlement_record (id),
    CONSTRAINT uq_outcome_settlement UNIQUE (outcome_id, settlement_id)
);
